describe('tests governing documentation', () => {
    it('opens and adds new', () => {
        cy.login('QA_user', 'zIaNuhpGz8uxZRazhSCU')
        cy.wait(750)
        cy.get('body').then($body => {
            if ($body.find('.Vue-Toastification__close-button').length > 0) {
                cy.get('.Vue-Toastification__close-button').click()
            }
        })
        cy.switchTenant('cypressTenantProto')
        cy.wait(750)
        cy.openManagement('Compliance', 'Governing Documentation')
        cy.wait(750)
        cy.contains('Add').click()
        cy.wait(750)
        
        //input of new governing doc
        cy.get('#name').type('A special Document')
        cy.get('#description').type('Brief description')
        cy.get('#owner').click()
        cy.wait(750)
        cy.get('#owner_0').click()
        cy.wait(750)
        cy.get('.p-inputmask').type('11111')
        cy.contains('Link').parent().find('input').type('https://google.com/')
        cy.get('.primary-btn').eq(1).click()
        cy.get('.list__body-elem').should('have.length', '3')
        cy.get('a > .p-button').click()
        cy.wait(1750)
        cy.get('tbody').last().find('.list__body-elem').as('requirements')
        cy.get('@requirements').eq(0).children().eq(2).click()
        cy.get('@requirements').eq(0).click()
        cy.get('textarea').click()
        cy.get('textarea').type('test of description text')
        cy.contains('Save').click()
        cy.get('.Vue-Toastification__toast-body').should('have.text', 'Mapping saved successfully')
        cy.go(-1)
        cy.wait(750)
        cy.get('.px-2').click()
        cy.get('.Vue-Toastification__toast-component-body > .flex > p').should('contain', 'Generated Successfully')
        //mapps requirement and goes back to gov doc browser -> next assert new data -> generate report
        cy.wait(750)
        cy.deleteDataEntry()
        cy.get('[data-cy="menu_reports"] > .flex').click()
        cy.wait(750)
        cy.get('.list__body-elem').last().click()
        cy.contains('Open Report').click()
        cy.get('.overflow-auto > :nth-child(1) > :nth-child(2) > :nth-child(1) > :nth-child(2)').should('have.text','A special Document')
    })
})